server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: customer
    password: 1221
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance: # Эта настройка необходима каждому микросервису, к котому обращается сервис gateway
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
      web:
      client:
      RestTemplate: INFO
