### Запрос направляется в gateway, и только потом переадресовывается в customer
# @name createCustomerRegistory
POST http://localhost:8085/api/v1/customer
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Alen",
  "email": "alen@email.com"
}

###
