server:
  port: 8090

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5435/notification
    username: notification
    password: 1221
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO